version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat buildJvm buildJs --info --no-daemon

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

